# server config
server:
  port: 8080
  servlet:
    context-path: /


# spring druid config
spring:
  datasource:
    name: safasa
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/user?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root123

# spring mybatis config
mybatis:
  type-aliases-package: com.qfjy.bean
  mapper-locations: classpath:com/qfjy/mapper/*.xml